### PR TITLE
Update .NET Core Preview from v1 to v2

### PR DESCRIPTION
**Pull request by rogersachan**
Change to the official release of .NET Core and allows proper usage of NuGet as a result.

### CODE REVIEW

**Comment by rogersachan** [comment]
Please merge this soon, as it bricks anyone's attempt at using NuGet when using .NET Core Preview 1

**Comment by TylerJewell** [comment]
@eivantsov

**Comment by eivantsov** [comment]
https://hub.docker.com/r/codenvy/dotnet_core/builds/
Just updated

**Comment by rogersachan** [comment]
@eivantsov Is it possible that I could add https://github.com/OmniSharp/generator-aspnet via another pull request? The ASP.NET Core documentation (https://docs.asp.net/en/latest/client-side/yeoman.html ) suggests it because it gives a similar selection to Visual Studio.

**Pull request merged**
