### PR TITLE
fix apache2 confile file path

### PR DESCRIPTION
**Pull request by freewind**
Signed-off-by: Peng Li nowind_lee@qq.com

### CODE REVIEW

**Comment by TylerJewell** [comment]
Ok for me.  @eivantsov?

**Comment by eivantsov** [comment]
Did you have issues with running it as is?

**Comment by freewind** [comment]
@eivantsov It doesn't fail, but there are two results I see:

1. if I create projects following the "stack"  reminders and choose "php", the url for apache2 doesn't response (seems apache doesn't start well)

2. If I create my own recipe, it will give the default page of apache (shows some words to tell you the server is running), but now the projects root in che

**Comment by eivantsov** [comment]
Yes, there was a bug with apache start - fixed now. Pull the updated image.

As to preview url, you should append project name to the default URL. I changed document root to projects since it is impossible to know what projects, you should see the index of projects in /projects and clicking on project icon will open your index.php or index.html script if any.

FYI, in a new image, we do not start apache automatically. After a workspace starts, you have to start apache yourself.

Closing this PR for now.

**Pull request closed without merging**
