### PR TITLE
creating a Dockerfile for support dotnet core

### PR DESCRIPTION
**Pull request by mercuriete**
I'm am trying to get dotnet core working in eclipse che.

so first to create a template i should create a image with the enviroment.

I started from condenvy/ubuntu-jre
and then i modified the dockerfile to follow this tutorial:
https://www.microsoft.com/net/core#ubuntu

it is just installing a new key for apt-get
install the package and that it.

for test that the image is working:

dotnet new
dotnet restore
dotnet run

### CODE REVIEW

**Comment by mercuriete** [comment]
https://github.com/eclipse/che/issues/1373

**Comment by mercuriete** [comment]
I will cancel this pull request because it doesn't work properly.
I will try again later using FROM codenvy/ubuntu_jre

**Comment by TylerJewell** [comment]
I am surprised you are closing it.  Weren't you thinking of modifying this one to update it?

**Comment by TylerJewell** [comment]
https://github.com/codenvy/dockerfiles/tree/master/aspnet

**Comment by mercuriete** [comment]
@TylerJewell 

sorry I open it a new one:
https://github.com/codenvy/dockerfiles/pull/41

I created a new Dockerfile and not modifiying the existent because it seems that dotnet core is not "full profile" ASP.NET application or something like that.
Applications created for ASP.NET wont work in ASP.NET core. Its like a subset of ASP.NET

https://github.com/aspnet/cli-samples/issues/55

So for replacing the old asp.net enviroment with the new one, i still need to add dependency to mono and xbuild or keep it separated.

By the way I realized that you were the person who show me eclipse che by an inspiring presentation on youtube. Its an honor talk with you directly :smile:.

**Comment by TylerJewell** [comment]
@mercuriete - ok, makes sense that .net core is different from stack for asp.net.  Good luck with the pull request process.  Our engineers are very thorough.  Even some of our most professional engineers have to make quite a few edits before they get a merge :+1:

**Pull request closed without merging**
