### PR TITLE
Added in Yeoman ASPNET generator to DotNet Core (suggested for use of ASP.NET Core)

### PR DESCRIPTION
**Pull request by rogersachan**
This will make .NET Core usage easier and help install dependencies for ASP.NET core websites. Project page is here: (https://github.com/OmniSharp/generator-aspnet). Usage of the yeoman generator is suggested on non-windows platforms on the ASP.NET Docs site (https://docs.asp.net/en/latest/client-side/yeoman.html).

### CODE REVIEW

**Comment by rogersachan** [comment]
I unfortunately cannot test to see if those additions worked at the moment. Can anyone relay to me the success of the new dockerfile?

**Comment by rogersachan** [comment]
@ddementieva This was due to an error @ https://github.com/npm/npm/issues/13284 . The builds should start working as the next version of nodejs rolls out.

**Comment by rogersachan** [comment]
How do I force a new build when nodejs begins working again?

**Comment by ddementieva** [comment]
We've pushed image manually to the Dockerhub to avoid 502 error: https://hub.docker.com/r/codenvy/dotnet/

**Comment by rogersachan** [comment]
@ddementieva Attempting to manually run that gave me "Unable build docker based machine, Dockerfile found but it doesn't contain base image." on Codenvy, and why is it that we need to move it to a separate repo instead of rebuilding it?

**Comment by eivantsov** [comment]
How do you run the workspace? I have just tested and it works for me

**Comment by rogersachan** [comment]
@eivantsov If you look at https://hub.docker.com/r/codenvy/dotnet_core/builds/ which is the build that codenvy uses at the moment, since the build failed then it seems to have fallen back on the old dockerfile if you click dockerfile on that page. Please force a new build _ASAP_ that will bring back the 'yo aspnet' functionality. Any attempt at using the yo aspnet on codenvy fails if you were to attempt it right now, proving that the dockerfile was never built.

**Comment by rogersachan** [comment]
Can we please just fix the build that's offered on codenvy right now! All it should take it a new build, that's it!

**Comment by rogersachan** [comment]
@ddementieva has given a different image on a different page that isn't distributing or building an image at the moment

**Comment by rogersachan** [comment]
We just need to rebuild the on *this* page: https://hub.docker.com/r/codenvy/dotnet_core/builds/

*After the nodejs error it seems to have decided not to offer the new build with the packages Microsoft suggested, which breaks complete and proper usage of ASP.NET*

**Comment by TylerJewell** [comment]
@rogersachan - pls be patient.  there are behind-the-scenes tests & approvals that we go through on stuff, so the support engineers are running through that.

**Comment by rogersachan** [comment]
Alright then, but how exactly does it need to go through builds again if it's nodejs servers that went down and not the script

**Comment by rogersachan** [comment]
And it was approved up to that point so I'm  not exactly sure what kind of cycle that it

**Comment by TylerJewell** [comment]
We don't have all of this fully automated with CI as we are trying to get the images setup and structured so that they can be moved to EPL license and managed by Eclipse Foundation. So we are taking some behind the scenes manual steps to replicate a quasi acceptance process similar to what Eclipse would do.  

Eugene or Daria will update the push when they see this - they are the two that have access to this.

BTW - DockerHub on some of these builds, it's not fool proof.  So, these issues do show up from time to time.

**Comment by rogersachan** [comment]
@TylerJewell Alright then

**Pull request merged**
